# Generated by Django 2.2.dev20180602023146 on 2018-06-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=20)),
                ('color_hex', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=500, upload_to='')),
                ('id1', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='jewellery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewellery.Jewellery'),
        ),
    ]
