# Generated by Django 2.2.dev20180602023146 on 2018-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
