# Generated by Django 2.2.dev20180602023146 on 2018-06-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0002_dress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dress',
            table='dress',
        ),
    ]
